language: python

jobs:
  include:
    - name: "Python 3.6 on Linux"
      python: 3.6
      before_install:
        - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        - git submodule update --init --recursive
    - name: "Python 3.7 on Linux"
      python: 3.6
      before_install:
        - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        - git submodule update --init --recursive
    - name: "Python 3.8 on Linux"
      python: 3.8
      before_install:
        - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        - git submodule update --init --recursive
    - name: "Python 3.8 on Linux"
      python: 3.8
      before_install:
        - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        - git submodule update --init --recursive
    - name: "Python 3.7.4 on macOS"
      os: osx
      language: shell
      before_install:
        - brew update
        # - brew install python3
        - brew install gnu-sed
        - gsed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        - git submodule update --init --recursive

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules

install: 
  - pip3 install -e .
  - pip3 install -r dev-requirements.txt

script:
  - flake8
  - python3 -m pytest tests/
